# Docker Compose file for ELK stack

# Build with:
# docker-compose build elk

# Run with:
# docker-compose up

elk:
  build: .
  ports:
    - "5601:5601"
    - "9200:9200"
    - "12201:12201/udp"
    - "5044:5044"
  ulimits:
    nofile:
      soft: "65536"
      hard: "65536"